name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set hash
        id: hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: |
           docker build . --file BlogSite/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/blogsite:latest --tag ${{ secrets.DOCKERHUB_USERNAME }}/blogsite:${{ steps.hash.outputs.sha_short }}
           docker push gcpease/blogsite:latest
           docker push gcpease/blogsite:${{env.git_hash}}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BLOG_HOST }}
          username: ${{ secrets.BLOG_USERNAME }}
          key : ${{ secrets.BLOG_KEY }}
          script: |
            docker stop blogsite
            docker rm blogsite
            docker pull gcpease/blogsite:latest
            docker run -v ~/blogsite-db:/db -v ~/blogsite-media:/app/Media -dp 80:80 --name blogsite gcpease/blogsite:latest 
    